format = """
${custom.cpu}${nodejs}${aws}${custom.review}
${all}${custom.caffeinated}${jobs}${character}
"""

[aws]
format = "[ ($profile) ($region) ($duration)]($style)"

[aws.region_aliases]
us-east-1 = "Virginia"
ap-northeast-2 = "Seoul"
ap-northeast-1 = "Tokyo"

[cmd_duration]
disabled = true

[directory]
truncation_length = 0
truncate_to_repo = false

[nodejs]
format = "[ $symbol$version]($style)"

# custom modules

[custom.caffeinated]
description = "Show coffee if you are caffeinated"
when = """ test "$CAFFEINATED" = true """
symbol = "☕️"
format = "$symbol "

[custom.cpu]
description = "arm64 OR x86"
command = "uname -m"
format = "[$output]($style)"
when = "true"
style = "bold blue"

