format = """
${nodejs}${aws}${custom.dynein}${custom.temp_env}
${all}${jobs}${character}
"""

[aws]
format = "[ ($profile) ($region)]($style)"

[aws.region_aliases]
us-east-1 = "Virginia"
ap-northeast-2 = "Seoul"
ap-northeast-1 = "Tokyo"

[cmd_duration]
disabled = true

[directory]
truncation_length = 0
truncate_to_repo = false

[nodejs]
format = "[$symbol$version]($style)"

[custom.dynein]
description = "show dynein table and region"
command = "open ~/.dynein/config.yml | $'($in.using_table) ($in.using_region)'"
format = " [$output]($style)"
when = '''"~/.dynein/config.yml" | path exists'''
style = "bold #FFA500"

[custom.temp_env]
command = "$env.temp"
format = " [$output]($style)"
when = "$env.temp? != null"
style = "gray"
