#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
COMMON_DIR="$ROOT/agent-common"
CODEX_DIR="$ROOT/codex"
CODEX_AGENTS="$CODEX_DIR/AGENTS.md"

tmp_file="$(mktemp "${CODEX_AGENTS}.tmp.XXXXXX")"
trap 'rm -f "$tmp_file"' EXIT

{
  printf '# AGENTS.md\n\n'
  printf '<!-- Generated by scripts/sync-agent-instructions.sh. Edit agent-common/*.md or codex/codex-specific.md instead. -->\n\n'
  awk '1' "$COMMON_DIR/global.md"
  printf '\n\n'
  awk '1' "$COMMON_DIR/won-judgment.md"
  printf '\n\n'
  awk '1' "$CODEX_DIR/codex-specific.md"
} > "$tmp_file"

mv "$tmp_file" "$CODEX_AGENTS"
trap - EXIT
